/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonDoc: typeof import('./src/views/uikit/ButtonDoc.vue')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    ChartDoc: typeof import('./src/views/uikit/ChartDoc.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClientesPage: typeof import('./src/views/pages/clientes/ClientesPage.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    copy: typeof import('./src/views/pages/auth/Login copy.vue')['default']
    Dashboard: typeof import('./src/views/Dashboard.vue')['default']
    DashboardDemo: typeof import('./src/views/DashboardDemo.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Empty: typeof import('./src/views/pages/Empty.vue')['default']
    FileDoc: typeof import('./src/views/uikit/FileDoc.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    Fluid: typeof import('primevue/fluid')['default']
    FormCliente: typeof import('./src/views/pages/clientes/FormCliente.vue')['default']
    FormLayout: typeof import('./src/views/uikit/FormLayout.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputDoc: typeof import('./src/views/uikit/InputDoc.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListaClientes: typeof import('./src/views/pages/clientes/ListaClientes.vue')['default']
    ListDoc: typeof import('./src/views/uikit/ListDoc.vue')['default']
    Login: typeof import('./src/views/pages/auth/Login.vue')['default']
    LoginSingle: typeof import('./src/views/pages/auth/LoginSingle.vue')['default']
    MediaDoc: typeof import('./src/views/uikit/MediaDoc.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    MenuDoc: typeof import('./src/views/uikit/MenuDoc.vue')['default']
    Message: typeof import('primevue/message')['default']
    MessagesDoc: typeof import('./src/views/uikit/MessagesDoc.vue')['default']
    MiscDoc: typeof import('./src/views/uikit/MiscDoc.vue')['default']
    OverlayDoc: typeof import('./src/views/uikit/OverlayDoc.vue')['default']
    PanelsDoc: typeof import('./src/views/uikit/PanelsDoc.vue')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelecionarEmpresa: typeof import('./src/views/pages/auth/SelecionarEmpresa.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SplitButton: typeof import('primevue/splitbutton')['default']
    TableDoc: typeof import('./src/views/uikit/TableDoc.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TimelineDoc: typeof import('./src/views/uikit/TimelineDoc.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    TreeDoc: typeof import('./src/views/uikit/TreeDoc.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
  }
}
